metadata/force-app/main/default/objects/LeanData_Custom_Interface_Settings__c/LeanData_Custom_Interface_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>LeanData Custom Interface Settings</label>
</CustomObject>

metadata/force-app/main/default/objects/LeanData_Custom_Interface_Settings__c/fields/Round_Robin_Field__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin_Field__c</fullName>
    <label>Round Robin Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/LeanData_Custom_Interface_Settings__c/fields/WHERE_Clause__c.field-meta.xml
<CustomField>
    <fullName>WHERE_Clause__c</fullName>
    <label>WHERE Clause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/classes/LeanDataCTABatch.cls
public class LeanDataCTABatch implements Database.Batchable<SObject>,Database.Stateful{
    

    public Database.QueryLocator start(Database.BatchableContext ctx){
        List<LeanData_Custom_Interface_Settings__c> result = [SELECT Round_Robin_Field__c, WHERE_Clause__c FROM LeanData_Custom_Interface_Settings__c];
        LeanData_Custom_Interface_Settings__c settings;
        if(result.size() > 0){
            settings = result[0];
        }
        
        if(settings != null)
            System.debug(settings);
        
        String query ='';
        //String roundRobinField = settings.Round_Robin_Field__c;
        String whereClause =  'name like'+ ' %Test';
        
        if(whereClause != null)
            System.debug(whereClause);
            query = 'Select' + ' Id,name from account limit ' + 1; 
        
        //query = 'SELECT ' + settings.Round_Robin_Field__c + ', Id FROM JBCXM__CTA__C Where (' + settings.WHERE_Clause__c + ')';
        
        if(query != null)
            System.debug(query);
        
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext ctx, List<SObject> sobjectScope){
       List<Id> objectIds = new List<Id>();
        for(Account cta : (List<Account>) sobjectScope){
            objectIds.add(cta.Id);
        }
        LeanDataCTARR.roundRobinCTAs(objectIds);
    }

    public void finish(Database.BatchableContext ctx){

    }
}