metadata/force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

metadata/force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

metadata/force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

metadata/force-app/main/default/objects/Account/recordTypes/Webdam.recordType-meta.xml
<RecordType>
    <fullName>Webdam</fullName>
    <active>true</active>
    <label>Webdam</label>
</RecordType>

metadata/force-app/main/default/objects/Adjacent_Technology__c/Adjacent_Technology__c.object-meta.xml
<CustomObject>
    <label>Adjacent Technology</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Technology Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjacent Technologies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/force-app/main/default/objects/Adjacent_Technology__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Adjacent Technologies</relationshipLabel>
    <relationshipName>Customer_Technologies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/force-app/main/default/objects/Adjacent_Technology__c/fields/Adjacent_Technology__c.field-meta.xml
<CustomField>
    <fullName>Adjacent_Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If technology is not listed, please select other and add name below.</inlineHelpText>
    <label>Adjacent Technology (Deprecated)</label>
    <referenceTo>Integration__c</referenceTo>
    <relationshipLabel>Adjacent Technologies (Dep)</relationshipLabel>
    <relationshipName>Adjacent_Technologies_Dep</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/Object_Info_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Object Info Settings</label>
    <pluralLabel>Object Info Settings</pluralLabel>
</CustomObject>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Display_Columns__c.field-meta.xml
<CustomField>
    <fullName>Display_Columns__c</fullName>
    <description>Number of columns to render in the LWC Object Info component.</description>
    <inlineHelpText>Number of columns to render in the LWC Object Info component.</inlineHelpText>
    <label>Display Columns</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>A comma delimited list of API field names for the target SObject and record type.</description>
    <inlineHelpText>A comma delimited list of API field names for the target SObject and record type.</inlineHelpText>
    <label>Fields</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/classes/SPGAccountController.cls
public without sharing class SPGAccountController {
    @AuraEnabled
    public static Model getModel(String accountId) {
        try {
            Account account = [SELECT Id, RecordType.DeveloperName FROM Account WHERE Id = :accountId WITH SECURITY_ENFORCED LIMIT 1];
            List<Object_Info_Setting__mdt> objectInfoSettings = SPGUtillity.getObjectInfoSettings('Account', account.RecordType.DeveloperName);
            List<Adjacent_Technology__c> technologies = getAdjacentTechnologies(account);
            return new Model(account, objectInfoSettings, technologies);
        } catch (QueryException e) {
            throw new FW_Exception('Invalid record id or missing configuration for record type.', true, e.getStackTraceString());
        } catch (Exception e) {
            throw new FW_Exception(e.getMessage(), true, e.getStackTraceString());
        }
    }

    private static List<Adjacent_Technology__c> getAdjacentTechnologies(Account a){
        return [
            SELECT Id
            FROM Adjacent_Technology__c
            WHERE Account__c =: a.Id
            WITH SECURITY_ENFORCED
        ];
    }

    public class Model {
        @AuraEnabled
        public String accountId { get; set; }
        @AuraEnabled
        public List<String> accountFields { get; set; }
        @AuraEnabled
        public Integer accountColumns { get; set; }
        @AuraEnabled
        public List<String> addressesFields { get; set; }
        @AuraEnabled
        public Integer addressesColumns { get; set; }
        @AuraEnabled
        public List<Adjacent_Technology__c> technologies { get; set; }
        @AuraEnabled
        public Map<String, Set<String>> technologyFields { get; set; }
        @AuraEnabled
        public Integer technologyColumns { get; set; }

        public Model() {
            this.accountFields = new List<String>();
            this.accountColumns = 1;
            this.addressesFields = new List<String>();
            this.addressesColumns = 1;
            this.technologyFields = new Map<String, Set<String>>();
        }

        public Model(Account account, List<Object_Info_Setting__mdt> objectInfoSettings, List<Adjacent_Technology__c> technologies) {
            this();
            Map<String, Object_Info_Setting__mdt> objectInfoSettingsByName = new Map<String, Object_Info_Setting__mdt>();
            for (Object_Info_Setting__mdt objectInfoSetting : objectInfoSettings) {
                objectInfoSettingsByName.put(objectInfoSetting.DeveloperName, objectInfoSetting);
            }

            String keyPrefix;
            switch on account.RecordType.DeveloperName {
                when 'Customer' {
                    keyPrefix = 'Account_Customer';
                }
                when 'Gartner_Buyer_Discovery' {
                    keyPrefix = 'Account_Buyer';
                }
                when 'Partner' {
                    keyPrefix = 'Account_Partner';
                }
                when 'Prospect' {
                    keyPrefix = 'Account_Prospect';
                }
                when 'Webdam' {
                    keyPrefix = 'Account_Webdam';
                }
            }

            this.accountId = account.Id;
            this.accountFields = objectInfoSettingsByName.get(keyPrefix).Fields__c.remove(' ').split(',');
            this.accountColumns = Integer.valueOf(objectInfoSettingsByName.get(keyPrefix).Display_Columns__c);
            this.addressesFields = objectInfoSettingsByName.get(keyPrefix + '_Addresses').Fields__c.remove(' ').split(',');
            this.addressesColumns = Integer.valueOf(objectInfoSettingsByName.get(keyPrefix + '_Addresses').Display_Columns__c);
            
            this.technologies = !technologies.isEmpty()? technologies : new List<Adjacent_Technology__c>();
            this.technologyFields.put('Adjacent Technology Details', getFields(objectInfoSettingsByName.get(keyPrefix + '_Technologies')));
            this.technologyFields.put('Confirmed Integration Details', getFields(objectInfoSettingsByName.get(keyPrefix + '_Integration')));
            this.technologyColumns = getColumns(objectInfoSettingsByName.get(keyPrefix + '_Technologies'));
        }

        private Set<String> getFields(Object_Info_Setting__mdt objectInfoSettings) {
            Set<String> fields = new Set<String>();
            for (String field : objectInfoSettings.Fields__c.remove(' ').split(',')) {
                fields.add(field);
            }
            return fields;
        }

        private Integer getColumns(Object_Info_Setting__mdt objectInfoSettings) {
            return Integer.valueOf(objectInfoSettings.Display_Columns__c);
        }
    }
}