metadata/force-app/main/default/objects/Lead/fields/Industry_from_Form__c.field-meta.xml
<CustomField>
    <fullName>Industry_from_Form__c</fullName>
    <label>Industry from Form (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Industry_from_G2Crowd__c.field-meta.xml
<CustomField>
    <fullName>Industry_from_G2Crowd__c</fullName>
    <label>Industry from G2Crowd (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Inferred_Country__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Country__c</fullName>
    <description>Webdam fields</description>
    <label>Inferred Country</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Inferred_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Postal_Code__c</fullName>
    <description>Webdam fields</description>
    <label>Inferred Postal Code</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Inferred_State_Region__c.field-meta.xml
<CustomField>
    <fullName>Inferred_State_Region__c</fullName>
    <description>webdam fields</description>
    <label>Inferred State Region (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score__c</fullName>
    <label>Lead Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Lead_Scoring__c</fullName>
    <formula>0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Score based on previous conversion data to help prioritise leads. In other words: how higher the score, the better the lead.</inlineHelpText>
    <label>Lead Scoring</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Description__c</fullName>
    <description>webdam fields</description>
    <label>Lead Source Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Source_Detailed__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Detailed__c</fullName>
    <description>webdam fields</description>
    <label>Lead Source Detailed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HOW Design Live 2014</fullName>
            </value>
            <value>
                <fullName>CASE List 01/08/09</fullName>
            </value>
            <value>
                <fullName>CA Schools - Mar/Comm</fullName>
            </value>
            <value>
                <fullName>Web Search - US Univ</fullName>
            </value>
            <value>
                <fullName>UPAA List</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>CoSIDA</fullName>
            </value>
            <value>
                <fullName>Jigsaw</fullName>
            </value>
            <value>
                <fullName>MDR</fullName>
            </value>
            <value>
                <fullName>UCDA 2010</fullName>
            </value>
            <value>
                <fullName>Visistat</fullName>
            </value>
            <value>
                <fullName>Love Your Brand Virtual Event</fullName>
            </value>
            <value>
                <fullName>Elance Lead Gen</fullName>
            </value>
            <value>
                <fullName>Danaher Companies</fullName>
            </value>
            <value>
                <fullName>eMotion Customers</fullName>
            </value>
            <value>
                <fullName>Tour &amp; Travel</fullName>
            </value>
            <value>
                <fullName>Pepsico Brands</fullName>
            </value>
            <value>
                <fullName>Cloud Vendors</fullName>
            </value>
            <value>
                <fullName>Dreamforce/Cloud</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Other web source</fullName>
            </value>
            <value>
                <fullName>UCDA 2012 Riverside</fullName>
            </value>
            <value>
                <fullName>Brand Management in Higher Ed Webinar</fullName>
            </value>
            <value>
                <fullName>Brandworkz</fullName>
            </value>
            <value>
                <fullName>CASE V 2012</fullName>
            </value>
            <value>
                <fullName>Application - Referral Partner</fullName>
            </value>
            <value>
                <fullName>Application - Technology Partner</fullName>
            </value>
            <value>
                <fullName>Application - Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Referral - Referral Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Marketo_State_Value__c.field-meta.xml
<CustomField>
    <fullName>Marketo_State_Value__c</fullName>
    <description>WD field</description>
    <label>Marketo State Value</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>webdam fields</description>
    <label>Most Recent Source</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Most_Recent_Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source_Description__c</fullName>
    <description>webdam fields</description>
    <label>Most Recent Source Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Most_Recent_Source_Detailed__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source_Detailed__c</fullName>
    <description>Webdam fields</description>
    <label>Most Recent Source Detailed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <label>Number of Employees (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;250</fullName>
            </value>
            <value>
                <fullName>250-2500</fullName>
            </value>
            <value>
                <fullName>2500-15000</fullName>
            </value>
            <value>
                <fullName>15000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Original_Lead_Source__c</fullName>
    <description>wd field
Acquired List 
US University Self Generated 
Website Corporate Inquiry 
WebDAM 
Content Request 
CASE DVII 2011 List 
Prospecting 
Shutterstock BLACKLISTED</description>
    <label>Original Lead Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Original_Referrer__c</fullName>
    <description>webdam fields</description>
    <label>Original Referrer</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Search_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Original_Search_Phrase__c</fullName>
    <description>webdam fields</description>
    <label>Original Search Phrase</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Original_Source_Type__c</fullName>
    <description>webdam fields</description>
    <label>Original Source Type</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/classes/MarketoLeadUpdateWebservice.cls
/* 
* - Site name:          https://full-bynder.cs14.force.com/
* - Relative endpoint:  /services/apexrest/<urlMapping>
*/
public class MarketoLeadUpdateWebservice {
    public MarketoLeadUpdateWebservice (){}
    // Class deprecated. No longer in use.
/* @RestResource(urlMapping='/updatelead/*')
global class MarketoLeadUpdateWebservice {
    
    @HttpGet
    global static void doGet(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        String resBody = '';
        try{
            ID leadId = req.params.get('lead_id');
            
            List<Lead> l = [SELECT Industry,Lead_Scoring__c, Lead_Source_Description__c,Lead_Source_Detailed__c,Most_Recent_Source_Description__c,Inferred_Postal_Code__c,LeadSource,
                     Most_Recent_Source_Detailed__c,Most_Recent_Source__c,Number_of_Employees__c,Original_Lead_Source__c,Original_Referrer__c,Industry_from_Form__c,Industry_from_G2Crowd__c,
                     Original_Source_Type__c,Phone,Inferred_State_Region__c,Marketo_State_Value__c,Inferred_Country__c,Lead_Score__c ,Original_Search_Phrase__c FROM LEAD WHERE id=:leadId LIMIT 1];
            
            if(l.size()>0){
            l[0].Industry = req.params.get('industry');
            l[0].Industry_from_G2Crowd__c = req.params.get('Industry_from_Form'); 
            l[0].Industry_from_Form__c = req.params.get('Industry_from_G2Crowd');
            l[0].Original_Search_Phrase__c = req.params.get('Original_Search_Phrase');
            l[0].Lead_Score__c = Decimal.valueOf(req.params.get('leadScore'));
            l[0].LeadSource= req.params.get('leadSource');
            l[0].Lead_Source_Description__c = req.params.get('Lead_Source_Description');
            l[0].Lead_Source_Detailed__c = req.params.get('Lead_Source_Detailed');
            l[0].Most_Recent_Source_Description__c = req.params.get('Most_Recent_Source_Description');
            l[0].Most_Recent_Source_Detailed__c = req.params.get('Most_Recent_Source_Detailed');
            l[0].Most_Recent_Source__c = req.params.get('Most_Recent_Source');
            //String Most_Recent_Source_contact = req.params.get('Most_Recent_Source_contact');
            l[0].Number_of_Employees__c = req.params.get('numberOfEmployees');
            l[0].Original_Lead_Source__c = req.params.get('Original_Lead_Source');
            l[0].Original_Referrer__c = req.params.get('Original_Referrer');
            l[0].Original_Source_Type__c = req.params.get('Original_Source_Type');
            l[0].Phone = req.params.get('phone');
            l[0].Inferred_Postal_Code__c= req.params.get('statecode');
            l[0].Inferred_Country__c = req.params.get('country');
            l[0].Inferred_State_Region__c = req.params.get('inferredStateRegion');

            update l;
            res.statusCode = 200;
            resBody = '{"success": true}';
            }

        }catch (Exception e){
            res.statusCode = 500;
            resBody = '{"success": false,"Exception:": '+e+'}';
            System.debug('Exception: '+e);
        }
        res.responseBody = Blob.valueOf(resBody);
    }
    
}*/}