metadata/force-app/main/default/objects/Lead/fields/Industry_from_Form__c.field-meta.xml
<CustomField>
    <fullName>Industry_from_Form__c</fullName>
    <label>Industry from Form (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Industry_from_G2Crowd__c.field-meta.xml
<CustomField>
    <fullName>Industry_from_G2Crowd__c</fullName>
    <label>Industry from G2Crowd (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Inferred_Country__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Country__c</fullName>
    <description>Webdam fields</description>
    <label>Inferred Country</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Inferred_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Postal_Code__c</fullName>
    <description>Webdam fields</description>
    <label>Inferred Postal Code</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Inferred_State_Region__c.field-meta.xml
<CustomField>
    <fullName>Inferred_State_Region__c</fullName>
    <description>webdam fields</description>
    <label>Inferred State Region (Deprecated)</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score__c</fullName>
    <label>Lead Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Description__c</fullName>
    <description>webdam fields</description>
    <label>Lead Source Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Lead_Source_Detailed__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Detailed__c</fullName>
    <description>webdam fields</description>
    <label>Lead Source Detailed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HOW Design Live 2014</fullName>
            </value>
            <value>
                <fullName>CASE List 01/08/09</fullName>
            </value>
            <value>
                <fullName>CA Schools - Mar/Comm</fullName>
            </value>
            <value>
                <fullName>Web Search - US Univ</fullName>
            </value>
            <value>
                <fullName>UPAA List</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>CoSIDA</fullName>
            </value>
            <value>
                <fullName>Jigsaw</fullName>
            </value>
            <value>
                <fullName>MDR</fullName>
            </value>
            <value>
                <fullName>UCDA 2010</fullName>
            </value>
            <value>
                <fullName>Visistat</fullName>
            </value>
            <value>
                <fullName>Love Your Brand Virtual Event</fullName>
            </value>
            <value>
                <fullName>Elance Lead Gen</fullName>
            </value>
            <value>
                <fullName>Danaher Companies</fullName>
            </value>
            <value>
                <fullName>eMotion Customers</fullName>
            </value>
            <value>
                <fullName>Tour &amp; Travel</fullName>
            </value>
            <value>
                <fullName>Pepsico Brands</fullName>
            </value>
            <value>
                <fullName>Cloud Vendors</fullName>
            </value>
            <value>
                <fullName>Dreamforce/Cloud</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Other web source</fullName>
            </value>
            <value>
                <fullName>UCDA 2012 Riverside</fullName>
            </value>
            <value>
                <fullName>Brand Management in Higher Ed Webinar</fullName>
            </value>
            <value>
                <fullName>Brandworkz</fullName>
            </value>
            <value>
                <fullName>CASE V 2012</fullName>
            </value>
            <value>
                <fullName>Application - Referral Partner</fullName>
            </value>
            <value>
                <fullName>Application - Technology Partner</fullName>
            </value>
            <value>
                <fullName>Application - Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Referral - Referral Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Marketo_State_Value__c.field-meta.xml
<CustomField>
    <fullName>Marketo_State_Value__c</fullName>
    <description>WD field</description>
    <label>Marketo State Value</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>webdam fields</description>
    <label>Most Recent Source</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Most_Recent_Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source_Description__c</fullName>
    <description>webdam fields</description>
    <label>Most Recent Source Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Most_Recent_Source_Detailed__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source_Detailed__c</fullName>
    <description>Webdam fields</description>
    <label>Most Recent Source Detailed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <label>Number of Employees (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;250</fullName>
            </value>
            <value>
                <fullName>250-2500</fullName>
            </value>
            <value>
                <fullName>2500-15000</fullName>
            </value>
            <value>
                <fullName>15000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Original_Lead_Source__c</fullName>
    <description>wd field
Acquired List 
US University Self Generated 
Website Corporate Inquiry 
WebDAM 
Content Request 
CASE DVII 2011 List 
Prospecting 
Shutterstock BLACKLISTED</description>
    <label>Original Lead Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Original_Referrer__c</fullName>
    <description>webdam fields</description>
    <label>Original Referrer</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Search_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Original_Search_Phrase__c</fullName>
    <description>webdam fields</description>
    <label>Original Search Phrase</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Original_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Original_Source_Type__c</fullName>
    <description>webdam fields</description>
    <label>Original Source Type</label>
    <type>TextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Lead/fields/Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>Other_Phone__c</fullName>
    <description>Webdam field</description>
    <label>Other Phone</label>
    <type>Phone</type>
</CustomField>

metadata/force-app/main/default/classes/MarketoLeadUpdateWebserviceTest.cls
@isTest
public class MarketoLeadUpdateWebserviceTest {

    @isTest
    public static void runPositiveTest(){
        MarketoLeadUpdateWebservice deprecated = new MarketoLeadUpdateWebservice();
        /* Lead l = new Lead(firstname='test',lastname='test',Status='Marketing 1: Not assessed',Company='test',LeadSource='hj',Inferred_Postal_Code__c='23',Most_Recent_Source_Detailed__c='test',Most_Recent_Source__c='test',Lead_Source_Description__c='test',Industry='Chemical and Energy and Agriculture',Lead_Source_Detailed__c='HOW Design Live 2014',Most_Recent_Source_Description__c='test',Number_of_Employees__c='12',Original_Lead_Source__c='test',Original_Referrer__c='wtest',Industry_from_Form__c='t', Industry_from_G2Crowd__c='test',Original_Source_Type__c='test',Other_Phone__c='test',Inferred_State_Region__c='test',Marketo_State_Value__c='test',Inferred_Country__c='test',Lead_Score__c=4,Phone='2333',Original_Search_Phrase__c='df');
        insert l;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestUri = '/services/apexrest/updatelead';
        req.httpMethod = 'GET';
        req.addParameter('lead_id', l.id);
        req.addParameter('industry', l.Industry);
        req.addParameter('Industry_from_G2Crowd', l.Industry_from_Form__c);
        req.addParameter('Industry_from_Form', l.Industry_from_G2Crowd__c);
        req.addParameter('Lead_Source_Description', l.Lead_Source_Description__c);
        req.addParameter('LeadSource', l.LeadSource);
        req.addParameter('Lead_Source_Detailed', l.Lead_Source_Detailed__c);
        req.addParameter('Most_Recent_Source_Description', l.Most_Recent_Source_Description__c);
        req.addParameter('numberOfEmployees', l.Number_of_Employees__c);
        req.addParameter('Original_Lead_Source', l.Original_Lead_Source__c);
        req.addParameter('phone', l.Phone);
        req.addParameter('inferredStateRegion', l.Inferred_State_Region__c);
        req.addParameter('statecode', l.Inferred_Postal_Code__c);
        req.addParameter('country', l.Inferred_Country__c);
        req.addParameter('Original_Search_Phrase', l.Original_Search_Phrase__c);
        req.addParameter('leadScore', String.valueOf(l.Lead_Score__c));
        req.addParameter('Most_Recent_Source_Detailed', l.Most_Recent_Source_Detailed__c);
        req.addParameter('Most_Recent_Source', l.Most_Recent_Source__c);
        req.addParameter('Original_Referrer', l.Original_Referrer__c);
        req.addParameter('Original_Source_Type', l.Original_Source_Type__c);

        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        MarketoLeadUpdateWebservice.doGet();
        Test.stopTest(); */
    }
    /*
    @isTest
    public static void runNegativeTest(){
                
        Lead l = new Lead(firstname='test',lastname='test',Status='Marketing 1: Not assessed',Company='test',LeadSource='hj',Inferred_Postal_Code__c='23',Most_Recent_Source_Detailed__c='test',Most_Recent_Source__c='test',Lead_Source_Description__c='test',Industry='Chemical and Energy and Agriculture',Lead_Source_Detailed__c='HOW Design Live 2014',Most_Recent_Source_Description__c='test',Number_of_Employees__c='12',Original_Lead_Source__c='test',Original_Referrer__c='wtest',Industry_from_Form__c='t', Industry_from_G2Crowd__c='test',Original_Source_Type__c='test',Other_Phone__c='test',Inferred_State_Region__c='test',Marketo_State_Value__c='test',Inferred_Country__c='test',Lead_Score__c=4,Phone='2333',Original_Search_Phrase__c='df');
        insert l;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.addParameter('lead_id', l.id+'d');
        req.requestUri = '/services/apexrest/updatelead';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        MarketoLeadUpdateWebservice.doGet();
        Test.stopTest();
    }*/
}