metadata/force-app/main/default/objects/Object_Info_Setting__mdt/Object_Info_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Object Info Settings</label>
    <pluralLabel>Object Info Settings</pluralLabel>
</CustomObject>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Display_Columns__c.field-meta.xml
<CustomField>
    <fullName>Display_Columns__c</fullName>
    <description>Number of columns to render in the LWC Object Info component.</description>
    <inlineHelpText>Number of columns to render in the LWC Object Info component.</inlineHelpText>
    <label>Display Columns</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>A comma delimited list of API field names for the target SObject and record type.</description>
    <inlineHelpText>A comma delimited list of API field names for the target SObject and record type.</inlineHelpText>
    <label>Fields</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>The API name for the SObject record type.</description>
    <inlineHelpText>The API name for the SObject record type.</inlineHelpText>
    <label>Record Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Addresses</fullName>
            </value>
            <value>
                <fullName>Spiced</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Competitors</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>Adjacent Technologies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/classes/SPGUtillity.cls
public without sharing class SPGUtillity {
    public static List<Object_Info_Setting__mdt> getObjectInfoSettings(String objectName, String recordTypeName){
        List<Object_Info_Setting__mdt> objectInfoSettings = new List<Object_Info_Setting__mdt>();
        // SOQL query is used to fetch metadata records as the getAll().Values() returns only the first 255 characters are returned for any field in a custom metadata type record, so longer text fields get truncated.
        for(Object_Info_Setting__mdt ois: [Select Id,DeveloperName,MasterLabel,Display_Columns__c,Fields__c,Record_Type__c,Section__c,Target_Object__c from Object_Info_Setting__mdt]){
        System.debug('Obj Metadata:'+ois);
            if(String.isBlank(objectName) || (ois.Target_Object__c == objectName && ois.Record_Type__c == recordTypeName)){
                objectInfoSettings.add(ois);
            }
        }
        System.debug('Obj Metadata List:'+objectInfoSettings);
        return objectInfoSettings;
    }
}