metadata/force-app/main/default/objects/Object_Info_Setting__mdt/Object_Info_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Object Info Settings</label>
    <pluralLabel>Object Info Settings</pluralLabel>
</CustomObject>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Display_Columns__c.field-meta.xml
<CustomField>
    <fullName>Display_Columns__c</fullName>
    <description>Number of columns to render in the LWC Object Info component.</description>
    <inlineHelpText>Number of columns to render in the LWC Object Info component.</inlineHelpText>
    <label>Display Columns</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Object_Info_Setting__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>A comma delimited list of API field names for the target SObject and record type.</description>
    <inlineHelpText>A comma delimited list of API field names for the target SObject and record type.</inlineHelpText>
    <label>Fields</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Default_Opportunity_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Default_Opportunity_Record_Type</fullName>
    <active>true</active>
    <businessProcess>Bynder</businessProcess>
    <description>This record type is for new business opportunities</description>
    <label>New Business</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Professional_Services_Opportunities.recordType-meta.xml
<RecordType>
    <fullName>Professional_Services_Opportunities</fullName>
    <active>true</active>
    <businessProcess>Bynder</businessProcess>
    <description>This record type should be used for opportunities where only professional services are charged</description>
    <label>Professional Services</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Referral.recordType-meta.xml
<RecordType>
    <fullName>Referral</fullName>
    <active>true</active>
    <businessProcess>Referral</businessProcess>
    <description>This is a record type for referral opportunities.</description>
    <label>Referral</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Referral_Closed.recordType-meta.xml
<RecordType>
    <fullName>Referral_Closed</fullName>
    <active>true</active>
    <businessProcess>Referral</businessProcess>
    <description>This record type is for closed referral opportunities.</description>
    <label>Referral - Closed</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Renewal_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Renewal_Record_Type</fullName>
    <active>true</active>
    <businessProcess>Renewal</businessProcess>
    <description>This record type is for renewals</description>
    <label>Renewal</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Upsell_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Upsell_Record_Type</fullName>
    <active>true</active>
    <businessProcess>Bynder</businessProcess>
    <description>This record type is for upsells</description>
    <label>Upsell</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/Opportunity_Competitors__c.object-meta.xml
<CustomObject>
    <label>Opportunity Competitors</label>
    <nameField>
        <displayFormat>Competitor-{000000}</displayFormat>
        <label>Opportunity Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <inlineHelpText>If competitor is not known please choose &quot;Unknown&quot; for competitor name. 
If competitor is not listed, please select other and add name below.</inlineHelpText>
    <label>Competitor</label>
    <referenceTo>Competitors__c</referenceTo>
    <relationshipLabel>Opportunity Competitors</relationshipLabel>
    <relationshipName>Competitor_Battles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Competitor_name_if_Other__c.field-meta.xml
<CustomField>
    <fullName>Competitor_name_if_Other__c</fullName>
    <description>If the competitor is not listed above, please select &apos;Other&apos; and include the name here.</description>
    <inlineHelpText>If the competitor is not listed above, please select &apos;Other&apos; and include the name here.</inlineHelpText>
    <label>Competitor name if &apos;Other&apos;</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Free text area to give more details on the competitor.</description>
    <inlineHelpText>Free text area to give more details on the competitor.</inlineHelpText>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Did_this_competitor_win_the_account__c.field-meta.xml
<CustomField>
    <fullName>Did_this_competitor_win_the_account__c</fullName>
    <description>Did this competitor win the account?</description>
    <inlineHelpText>Did this competitor win the account?</inlineHelpText>
    <label>Did this competitor win the account?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don&apos;t know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Is_this_the_current_tool_in_use__c.field-meta.xml
<CustomField>
    <fullName>Is_this_the_current_tool_in_use__c</fullName>
    <description>Is this competitor the current system in use?</description>
    <inlineHelpText>Is this competitor the current system in use?</inlineHelpText>
    <label>Is this the current tool in use?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don&apos;t know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Competitors</relationshipLabel>
    <relationshipName>Account_Opportunity_Competitors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Product_Reason__c.field-meta.xml
<CustomField>
    <fullName>Product_Reason__c</fullName>
    <description>Product loss reason is required when Product Capabilities is set as the loss reason.</description>
    <inlineHelpText>Product loss reason is required when Product Capabilities is set as the loss reason.</inlineHelpText>
    <label>Product Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DAM</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Digital Brand Templates</fullName>
            </value>
            <value>
                <fullName>Print Brand Templates</fullName>
            </value>
            <value>
                <fullName>Brand Guidelines</fullName>
            </value>
            <value>
                <fullName>Analytics</fullName>
            </value>
            <value>
                <fullName>API/Integrations</fullName>
            </value>
            <value>
                <fullName>File Type Support</fullName>
            </value>
            <value>
                <fullName>Permissions</fullName>
            </value>
            <value>
                <fullName>AI Capabilities</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Configurability</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Language support</fullName>
            </value>
            <value>
                <fullName>Asset tracking</fullName>
            </value>
            <value>
                <fullName>Usability</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_Competitors__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Please indicate why the opportunity was lost to the competitor.</description>
    <inlineHelpText>Please indicate why the opportunity was lost to the competitor.</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency Lost</fullName>
            </value>
            <value>
                <fullName>Analyst Feedback</fullName>
            </value>
            <value>
                <fullName>Blocker - Never got to Power/Key Stakeholders</fullName>
            </value>
            <value>
                <fullName>Cheaper Price/Better Offer</fullName>
            </value>
            <value>
                <fullName>Contract Terms</fullName>
            </value>
            <value>
                <fullName>Customer References</fullName>
            </value>
            <value>
                <fullName>Existing Relationship with Competitor</fullName>
            </value>
            <value>
                <fullName>Integrations Support</fullName>
            </value>
            <value>
                <fullName>Legal/Payment Terms Blocker</fullName>
            </value>
            <value>
                <fullName>Other (explain in &quot;Detail&quot; field)</fullName>
            </value>
            <value>
                <fullName>Product Capabilities within DAM</fullName>
            </value>
            <value>
                <fullName>Service Offering</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/classes/SPGOpportunityController.cls
public without sharing class SPGOpportunityController {
    @AuraEnabled
    public static Model getModel(String opportunityId) {
        try {
            Opportunity opportunity = getOpportunity(opportunityId);
            List<Opportunity_Competitors__c> competitors = getOpportunityCompetitors(opportunity);
            List<Opportunity_Competitors__c> currentVendors = getOpportunityCurrentVendors(opportunity);
            List<OpportunityPartner> partners = getPartners(opportunity);
            List<OpportunityContactRole> contactRoles = getOpportunityContactRoles(opportunity);
            List<Object_Info_Setting__mdt> objectInfoSettings = SPGUtillity.getObjectInfoSettings(null, opportunity.RecordType.DeveloperName);
            return new Model(opportunity, competitors, currentVendors, partners, contactRoles, objectInfoSettings);
        } catch (QueryException e) {
            throw new FW_Exception('Invalid record id or missing configuration for record type.', true, e.getStackTraceString());
        } catch (Exception e) {
            throw new FW_Exception(e.getMessage(), true, e.getStackTraceString());
        }
    }

    private static Opportunity getOpportunity(String opportunityId) {
        return [SELECT Id, AccountId, Account.RecordType.DeveloperName, RecordType.DeveloperName FROM Opportunity WHERE Id = :opportunityId WITH SECURITY_ENFORCED LIMIT 1];
    }

    private static List<Opportunity_Competitors__c> getOpportunityCompetitors(Opportunity opportunity) {
        return [
            SELECT
                Id,
                Opportunity__c,
                Competitor_name_if_Other__c,
                Competitor__c,
                Is_this_the_current_tool_in_use__c,
                Did_this_competitor_win_the_account__c,
                Product_Reason__c,
                Reason__c,
                Details__c
            FROM Opportunity_Competitors__c
            WHERE Opportunity__c = :opportunity.Id
            AND   Is_this_the_current_tool_in_use__c != 'Yes' 
            WITH SECURITY_ENFORCED
        ];
    }

    private static List<Opportunity_Competitors__c> getOpportunityCurrentVendors(Opportunity opportunity) {
        return [
            SELECT
                Id,
                Opportunity__c,
                Competitor_name_if_Other__c,
                Competitor__c,
                Is_this_the_current_tool_in_use__c,
                Did_this_competitor_win_the_account__c,
                Product_Reason__c,
                Reason__c,
                Details__c
            FROM Opportunity_Competitors__c
            WHERE Opportunity__c = :opportunity.Id
            AND   Is_this_the_current_tool_in_use__c = 'Yes' 
            WITH SECURITY_ENFORCED
        ];
    }

    private static List<OpportunityPartner> getPartners(Opportunity opportunity) {
        return [
            SELECT Id, AccountToId, AccountTo.Name, IsPrimary, Role
            FROM OpportunityPartner
            WHERE OpportunityId = :opportunity.Id AND AccountToId = :opportunity.AccountId
        ];
    }

    private static List<OpportunityContactRole> getOpportunityContactRoles(Opportunity opportunity) {
        return [SELECT Id, ContactId, Contact.Name, Role, IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opportunity.Id WITH SECURITY_ENFORCED];
    }

    public class Model {
        @AuraEnabled
        public String opportunityId { get; set; }
        @AuraEnabled
        public String opportunityRecordType { get; set; }
        @AuraEnabled
        public Set<String> opportunityFields { get; set; }
        @AuraEnabled
        public Set<String> opportunityNewBusinessFields { get; set; }
        @AuraEnabled
        public Integer opportunityColumns { get; set; }
        @AuraEnabled
        public Set<String> spicedFields { get; set; }
        @AuraEnabled
        public Integer spicedColumns { get; set; }
        @AuraEnabled
        public String accountId { get; set; }
        @AuraEnabled
        public Set<String> accountFields { get; set; }
        @AuraEnabled
        public Integer accountColumns { get; set; }
        @AuraEnabled
        public List<Opportunity_Competitors__c> competitors { get; set; }
        @AuraEnabled
        public Set<String> competitorFields { get; set; }
        @AuraEnabled
        public Integer competitorColumns { get; set; }
        @AuraEnabled
        public List<OpportunityPartner> partners { get; set; }
        @AuraEnabled
        public Set<String> partnerFields { get; set; }
        @AuraEnabled
        public Integer partnerColumns { get; set; }
        @AuraEnabled
        public List<OpportunityContactRole> contactRoles { get; set; }
        @AuraEnabled
        public Set<String> contactRoleFields { get; set; }
        @AuraEnabled
        public Integer contactRoleColumns { get; set; }
        @AuraEnabled
        public List<Opportunity_Competitors__c> currentVendors { get; set; }
        @AuraEnabled
        public Set<String> newBusinessTeamFields { get; set; }
        @AuraEnabled
        public Integer oppTeamColumns { get; set; }
        @AuraEnabled
        public Set<String> newBusinessSolutionsFields { get; set; }
        @AuraEnabled
        public Integer oppSolutionsColumns { get; set; }

        public Model() {
            this.opportunityFields = new Set<String>();
            this.opportunityNewBusinessFields = new Set<String>();
            this.opportunityColumns = 1;
            this.spicedFields = new Set<String>();
            this.spicedColumns = 1;
            this.accountFields = new Set<String>();
            this.accountColumns = 1;
            this.competitors = new List<Opportunity_Competitors__c>();
            this.currentVendors = new List<Opportunity_Competitors__c>();
            this.competitorFields = new Set<String>();
            this.competitorColumns = 1;
            this.partners = new List<OpportunityPartner>();
            this.partnerFields = new Set<String>();
            this.partnerColumns = 1;
            this.contactRoles = new List<OpportunityContactRole>();
            this.contactRoleFields = new Set<String>();
            this.contactRoleColumns = 1;
            this.newBusinessTeamFields = new Set<String>();
            this.oppTeamColumns = 1;
            this.newBusinessSolutionsFields = new Set<String>();
            this.oppSolutionsColumns = 1;
        }

        public Model(
            Opportunity opportunity,
            List<Opportunity_Competitors__c> competitors,
            List<Opportunity_Competitors__c> currentVendors,
            List<OpportunityPartner> partners,
            List<OpportunityContactRole> contactRoles,
            List<Object_Info_Setting__mdt> objectInfoSettings
        ) {
            Map<String, Object_Info_Setting__mdt> objectInfoSettingsByName = new Map<String, Object_Info_Setting__mdt>();
            for (Object_Info_Setting__mdt objectInfoSetting : objectInfoSettings) {
                objectInfoSettingsByName.put(objectInfoSetting.DeveloperName, objectInfoSetting);
            }

            String oppKeyPrefix;
            switch on opportunity.RecordType.DeveloperName {
                when 'Default_Opportunity_Record_Type' {
                    oppKeyPrefix = 'Opp_New_Business';
                }
                when 'Professional_Services_Opportunities' {
                    oppKeyPrefix = 'Opp_Professional_Services';
                }
                when 'Referral' {
                    oppKeyPrefix = 'Opp_Referral';
                }
                when 'Referral_Closed' {
                    oppKeyPrefix = 'Opp_Referral';
                }
                when 'Renewal_Record_Type' {
                    oppKeyPrefix = 'Opp_Renewal';
                }
                when 'Upsell_Record_Type' {
                    oppKeyPrefix = 'Opp_Upsell';
                }
            }

            this.opportunityId = opportunity.Id;
            this.opportunityRecordType = opportunity.RecordType.DeveloperName;
            this.opportunityFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix));
            this.opportunityColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix));
            this.spicedFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Spiced'));
            this.spicedColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Spiced'));
            this.accountId = opportunity.AccountId;
            if (oppKeyPrefix == 'Opp_New_Business') {
                this.opportunityNewBusinessFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Account'));
                this.newBusinessTeamFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Opp_Teams'));
                this.newBusinessSolutionsFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Solutions_Scope'));
                this.oppTeamColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Opp_Teams'));
                this.oppSolutionsColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Solutions_Scope'));
            }
            this.accountFields = getFields(objectInfoSettingsByName.get('Account_' + opportunity.Account.RecordType.DeveloperName));
            this.accountColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Account'));

            this.competitors = !competitors.isEmpty() ? competitors : new List<Opportunity_Competitors__c>();
            this.competitorFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Competitors'));
            this.competitorColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Competitors'));

            this.currentVendors = !currentVendors.isEmpty() ? currentVendors : new List<Opportunity_Competitors__c>();
        
            this.partners = !partners.isEmpty() ? partners : new List<OpportunityPartner>();
            this.partnerFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Partners'));
            this.partnerColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Partners'));
            
            this.contactRoles = !contactRoles.isEmpty() ? contactRoles : new List<OpportunityContactRole>();
            this.contactRoleFields = getFields(objectInfoSettingsByName.get(oppKeyPrefix + '_Contacts'));
            this.contactRoleColumns = getColumns(objectInfoSettingsByName.get(oppKeyPrefix + '_Contacts'));
        }

        private Set<String> getFields(Object_Info_Setting__mdt objectInfoSettings) {
            Set<String> fields = new Set<String>();
            for (String field : objectInfoSettings.Fields__c.remove(' ').split(',')) {
                fields.add(field);
            }
            return fields;
        }

        private Integer getColumns(Object_Info_Setting__mdt objectInfoSettings) {
            return Integer.valueOf(objectInfoSettings.Display_Columns__c);
        }
    }
}