metadata/force-app/main/default/objects/Account/fields/Company_Size_New__c.field-meta.xml
<CustomField>
    <fullName>Company_Size_New__c</fullName>
    <label>Company Size New</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Size</valueSetName>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Group</valueSetName>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/fields/Loss_Reason_Detail__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason_Detail__c</fullName>
    <label>Loss Reason Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Next_Steps_History__c.field-meta.xml
<CustomField>
    <fullName>Next_Steps_History__c</fullName>
    <description>Please keep a history of previous Next steps here</description>
    <label>Next Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amsterdam</fullName>
            </value>
            <value>
                <fullName>Boston</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Melbourne</fullName>
            </value>
            <value>
                <fullName>San Carlos</fullName>
            </value>
            <value>
                <fullName>San Mateo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>CTA Marketing</fullName>
            </value>
            <value>
                <fullName>Behavioral Marketing</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Event Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/globalValueSets/Company_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>MM - Small</fullName>
    </customValue>
    <customValue>
        <fullName>MM - Large</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Micro</fullName>
    </customValue>
    <masterLabel>Company Size</masterLabel>
</GlobalValueSet>

metadata/force-app/main/default/globalValueSets/Industry_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consumer Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Education and Government and Non-Profit</fullName>
    </customValue>
    <customValue>
        <fullName>Finance and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality and Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Industrials</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and Consulting and Media</fullName>
    </customValue>
    <customValue>
        <fullName>Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <masterLabel>Industry Group</masterLabel>
</GlobalValueSet>

metadata/force-app/main/default/classes/LossReasonEnteredTest.cls
@isTest

public class LossReasonEnteredTest {
    @isTest static void UpdateLossReason() {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Website = 'http://test.com';
        acc.CurrencyIsoCode = 'EUR';
        acc.Type = 'Prospect';
        acc.RecordTypeId = '0120P000000asyz';
        acc.BillingCountry = 'Austria';
        acc.Industry_Group__c = 'Consumer Brands';
        acc.Company_Size_New__c = 'SMB';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity name';
        opp.Type = 'New Business-Enterprise Cloud';
        opp.AccountId = acc.Id;
        opp.Next_Steps_History__c = 'Sell the product';
        opp.CloseDate = date.Today() + 90;
        opp.StageName = 'Qualified';
        opp.Sales_Office__c = 'Amsterdam';
        opp.CurrencyIsoCode = 'EUR';
        opp.Source__c = 'Outbound Sales';
        opp.RecordTypeId = '0120P000000QxSt';
        insert opp;
        
        opp.Loss_Reason_Detail__c = 'Test';
        update opp;
    }
}