metadata/force-app/main/default/objects/Account/fields/Company_Size_New__c.field-meta.xml
<CustomField>
    <fullName>Company_Size_New__c</fullName>
    <label>Company Size New</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Size</valueSetName>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Group</valueSetName>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity/fields/Contract_Renewal_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Renewal_Term__c</fullName>
    <description>The number of months in the renewal contract. e.g. contract 2 will be for 24 months.</description>
    <inlineHelpText>The number of months in the renewal contract. e.g. contract 2 will be for 24 months.</inlineHelpText>
    <label>Contract Renewal Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/End_date_contract__c.field-meta.xml
<CustomField>
    <fullName>End_date_contract__c</fullName>
    <inlineHelpText>Only to be filled out AFTER the contract has been signed.</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Invoice_period__c.field-meta.xml
<CustomField>
    <fullName>Invoice_period__c</fullName>
    <inlineHelpText>Will we invoice them 12 months upfront or per e.g. 6 months?</inlineHelpText>
    <label>Invoice period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/New_MRR__c.field-meta.xml
<CustomField>
    <fullName>New_MRR__c</fullName>
    <label>New MRR</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Notice_period_months__c.field-meta.xml
<CustomField>
    <fullName>Notice_period_months__c</fullName>
    <inlineHelpText>Number of months notice required to cancel contract.</inlineHelpText>
    <label>Notice period (months)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Payment_Period__c.field-meta.xml
<CustomField>
    <fullName>Payment_Period__c</fullName>
    <description>The time period in which the customer must pay fees and charges e.g. no later than 30 days after the invoice date</description>
    <inlineHelpText>The time period in which the customer must pay fees and charges e.g. no later than 30 days after the invoice date</inlineHelpText>
    <label>Payment Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>15 days</fullName>
            </value>
            <value>
                <fullName>30 days</fullName>
            </value>
            <value>
                <fullName>45 days</fullName>
            </value>
            <value>
                <fullName>60 days</fullName>
            </value>
            <value>
                <fullName>75 days</fullName>
            </value>
            <value>
                <fullName>90 days</fullName>
            </value>
            <value>
                <fullName>120 days</fullName>
            </value>
            <value>
                <fullName>30 Days ME</fullName>
            </value>
            <value>
                <fullName>60 Days ME</fullName>
            </value>
            <value>
                <fullName>90 Days ME</fullName>
            </value>
            <value>
                <fullName>150 days</fullName>
            </value>
            <value>
                <fullName>180 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Startdate_contract__c.field-meta.xml
<CustomField>
    <fullName>Startdate_contract__c</fullName>
    <inlineHelpText>Only to be filled out AFTER the contract has been signed.</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/Opportunity_ARR_Movement__c.object-meta.xml
<CustomObject>
    <description>This object contains ARR movements of opportunities.</description>
    <label>Opportunity ARR Movement</label>
    <nameField>
        <label>Opportunity ARR Movement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity ARR Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Lookup to the related opportunity.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity ARR Movements</relationshipLabel>
    <relationshipName>Opportunity_ARR_Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/force-app/main/default/globalValueSets/Company_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>MM - Small</fullName>
    </customValue>
    <customValue>
        <fullName>MM - Large</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Micro</fullName>
    </customValue>
    <masterLabel>Company Size</masterLabel>
</GlobalValueSet>

metadata/force-app/main/default/globalValueSets/Industry_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consumer Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Education and Government and Non-Profit</fullName>
    </customValue>
    <customValue>
        <fullName>Finance and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality and Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Industrials</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and Consulting and Media</fullName>
    </customValue>
    <customValue>
        <fullName>Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <masterLabel>Industry Group</masterLabel>
</GlobalValueSet>

metadata/force-app/main/default/classes/manageOpportunityARRMovementsTest.cls
@isTest
public class manageOpportunityARRMovementsTest {
    
    @testSetup static void createTestData(){
        Account acc = new Account(Name ='Test Account',Type ='Prospect',Website='www.C-a.com',Industry_Group__c ='Consumer Brands',
                                  Company_Size_New__c ='SMB');
        insert acc;
        Opportunity opp = new Opportunity(accountid=acc.id,Type='New Business-Enterprise Cloud',Name='Test Account - Contract 1',CloseDate =date.newInstance(2021,12,12),
                                          StageName='Signature Stage',Startdate_contract__c =date.newInstance(2021,12,25),End_date_contract__c=date.newInstance(2022,12,24),
                                          Contract_Renewal_Term__c =12.00,Invoice_period__c =12.00,Payment_Period__c ='15 days',Notice_period_months__c =2.00,New_MRR__c  =1000.00);
        insert opp;     
    }
    
    static testmethod void testOppMovements(){
        Opportunity testOpp = [Select id,stagename, New_MRR__c from opportunity where name ='Test Account - Contract 1'];
        testOpp.New_MRR__c  =2000.00;
        update testOpp;
        list<Opportunity_ARR_Movement__c> mvmtsList = [select id from Opportunity_ARR_Movement__c where opportunity__c =:testOpp.Id];
        system.assertNotEquals(0, mvmtsList.size());
    }
    
}