metadata/force-app/main/default/objects/Account/fields/Company_Size_New__c.field-meta.xml
<CustomField>
    <fullName>Company_Size_New__c</fullName>
    <label>Company Size New</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Size</valueSetName>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Account/fields/Industry_Group__c.field-meta.xml
<CustomField>
    <fullName>Industry_Group__c</fullName>
    <label>Industry Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry_Group</valueSetName>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

metadata/force-app/main/default/globalValueSets/Company_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SMB</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Market</fullName>
    </customValue>
    <customValue>
        <fullName>MM - Small</fullName>
    </customValue>
    <customValue>
        <fullName>MM - Large</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Micro</fullName>
    </customValue>
    <masterLabel>Company Size</masterLabel>
</GlobalValueSet>

metadata/force-app/main/default/globalValueSets/Industry_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consumer Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Education and Government and Non-Profit</fullName>
    </customValue>
    <customValue>
        <fullName>Finance and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality and Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Industrials</fullName>
    </customValue>
    <customValue>
        <fullName>Legal and Real Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and Consulting and Media</fullName>
    </customValue>
    <customValue>
        <fullName>Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <masterLabel>Industry Group</masterLabel>
</GlobalValueSet>

metadata/force-app/main/default/classes/pushAccountToJiraTest.cls
@isTest public class pushAccountToJiraTest {
    @isTest static void testTriggerAfterUpdate() {
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Website = 'http://test.com';
        acc.CurrencyIsoCode = 'EUR';
        acc.Type = 'Prospect';
        acc.RecordTypeId = '0120P000000asyz';
        acc.BillingCountry = 'Austria';
        acc.Industry_Group__c = 'Consumer Brands';
        acc.Company_Size_New__c = 'SMB';
        insert acc;
        
        acc.Jira_Issue__c ='BODEV-1234';
        update acc;
        
        //JCFS.JiraTriggerTestHelper.testAfterUpdate('Account');
    }
}