metadata/force-app/main/default/objects/Account/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <description>Used in Company object in Gainsight connect</description>
    <label>OEM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acquia</fullName>
            </value>
            <value>
                <fullName>Workfront</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to make sure we can automatically invoice the OEM partner with the existing sales order flow</description>
    <label>OEM / Partner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <filterItems>
            <field>Account.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (OEM)</relationshipLabel>
    <relationshipName>OEM</relationshipName>
    <type>Lookup</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Reporting_Date_to_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Date_to_Close_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is needed to be able to manually identify the Expansion movements on certain Renewals that were recognised on Close Date rather than Reporting date</description>
    <label>Reporting Date to Close Date</label>
    <type>Checkbox</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/fields/Startdate_contract__c.field-meta.xml
<CustomField>
    <fullName>Startdate_contract__c</fullName>
    <inlineHelpText>Only to be filled out AFTER the contract has been signed.</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <businessProcess>Bynder</businessProcess>
    <description>This record type is for closed opportunities.</description>
    <label>Closed</label>
</RecordType>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/Opportunity_ARR_Movement__c.object-meta.xml
<CustomObject>
    <description>This object contains ARR movements of opportunities.</description>
    <label>Opportunity ARR Movement</label>
    <nameField>
        <label>Opportunity ARR Movement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity ARR Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This field indicates the amount of the ARR value in FX</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Movement_Type__c.field-meta.xml
<CustomField>
    <fullName>Movement_Type__c</fullName>
    <description>This field indicates the type of the ARR movement record.</description>
    <label>Movement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New ARR</fullName>
            </value>
            <value>
                <fullName>New ARR: Platform Transfer</fullName>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
            <value>
                <fullName>Contraction</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
            <value>
                <fullName>Churn: Platform Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Internal Transfer</fullName>
            </value>
            <value>
                <fullName>New ARR: OEM</fullName>
            </value>
            <value>
                <fullName>Renewal Uplift</fullName>
            </value>
            <value>
                <fullName>Indexation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <description>Returns OEM value</description>
    <formula>IF(
  OR(
    CONTAINS(Opportunity__r.OEM__r.Name, &quot;Acquia&quot;),
    CONTAINS(Opportunity__r.OEM__r.Name, &quot;Workfront&quot;)
  ) &amp;&amp; NOT(CONTAINS(Opportunity__r.OEM__r.Name, &quot;Non OEM&quot;)),
  Opportunity__r.OEM__r.Name,
  &quot;&quot;
)</formula>
    <label>OEM</label>
    <type>Text</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Lookup to the related opportunity.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity ARR Movements</relationshipLabel>
    <relationshipName>Opportunity_ARR_Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Reporting_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Date__c</fullName>
    <description>Indicates Reporting Date of the movement.</description>
    <label>Reporting Date</label>
    <type>Date</type>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Opportunity_ARR_Movement__c/fields/Status_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Modified_Date__c</fullName>
    <label>Status Modified Date</label>
    <type>Date</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/Sales_KPI_Conditions__mdt.object-meta.xml
<CustomObject>
    <label>Sales KPI Conditions</label>
    <pluralLabel>Sales KPI Conditions</pluralLabel>
</CustomObject>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/ARR_Movement_Field__c.field-meta.xml
<CustomField>
    <fullName>ARR_Movement_Field__c</fullName>
    <inlineHelpText>Select the ARR movement field whose value has to be included as amount in the Opportunity ARR Movement records.</inlineHelpText>
    <label>ARR Movement Field</label>
    <metadataRelationshipControllingField>Sales_KPI_Conditions__mdt.Parent_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions5</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions5</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Criteria_logical_operator__c.field-meta.xml
<CustomField>
    <fullName>Criteria_logical_operator__c</fullName>
    <inlineHelpText>Select the logical operator for comparing the selected dates on opportunity.</inlineHelpText>
    <label>Criteria logical operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&gt;</fullName>
                <default>true</default>
                <label>&gt;</label>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Movement_Field__c.field-meta.xml
<CustomField>
    <fullName>Movement_Field__c</fullName>
    <inlineHelpText>Select the MRR movement field on whose change the Opportunity ARR movement has to be created or updated.</inlineHelpText>
    <label>Movement Field</label>
    <metadataRelationshipControllingField>Sales_KPI_Conditions__mdt.Parent_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Movement_Type__c.field-meta.xml
<CustomField>
    <fullName>Movement_Type__c</fullName>
    <inlineHelpText>Select the movement type</inlineHelpText>
    <label>Movement Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Churn</fullName>
                <default>true</default>
                <label>Churn</label>
            </value>
            <value>
                <fullName>Churn: Platform Transfer</fullName>
            </value>
            <value>
                <fullName>Contraction</fullName>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
            <value>
                <fullName>Internal Transfer</fullName>
            </value>
            <value>
                <fullName>New ARR</fullName>
            </value>
            <value>
                <fullName>New ARR: OEM</fullName>
            </value>
            <value>
                <fullName>New ARR: Platform Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Uplift</fullName>
            </value>
            <value>
                <fullName>Indexation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>Add different types of the opportunity applicable for the movements separated by semicolon.</inlineHelpText>
    <label>Opportunity Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>Select object related to sales KPI conditions (Opportunity)</inlineHelpText>
    <label>Parent Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Reporting_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Date__c</fullName>
    <inlineHelpText>Select the date field on opportunity which should be added as reporting date on Opportunity ARR movements.</inlineHelpText>
    <label>Reporting Date</label>
    <metadataRelationshipControllingField>Sales_KPI_Conditions__mdt.Parent_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions1</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Reporting_Date_Criteria_Field_1__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Date_Criteria_Field_1__c</fullName>
    <inlineHelpText>Select the date field to be compared for adding reporting date on Opportunity ARR Movement records.</inlineHelpText>
    <label>Reporting Date Criteria Field 1</label>
    <metadataRelationshipControllingField>Sales_KPI_Conditions__mdt.Parent_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions2</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Reporting_Date_Criteria_Field_2__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Date_Criteria_Field_2__c</fullName>
    <inlineHelpText>Select the date field to be compared for adding reporting date on Opportunity ARR Movement records.</inlineHelpText>
    <label>Reporting Date Criteria Field 2</label>
    <metadataRelationshipControllingField>Sales_KPI_Conditions__mdt.Parent_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions3</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions3</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/objects/Sales_KPI_Conditions__mdt/fields/Reporting_Date_to_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Date_to_Close_Date__c</fullName>
    <inlineHelpText>Select the field on opportunity used to update close date as reporting date.</inlineHelpText>
    <label>Reporting Date to Close Date</label>
    <metadataRelationshipControllingField>Sales_KPI_Conditions__mdt.Parent_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Sales_KPI_Conditions4</relationshipLabel>
    <relationshipName>Sales_KPI_Conditions4</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

metadata/force-app/main/default/classes/manageOpportunityARRMovements.cls
/***************************************************************
* * Class Name  : manageOpportunityARRMovements
* * Description : Class created for implementing the logic for creating or updating
* 				   Opportunity ARR Movements and this class is triggered from 'upsertOpportunityARRMovements' trigger
* 				   Opportunity
* *************************************************************/
public class manageOpportunityARRMovements {
    public Set<Id> oppIds = new set<id>();
    public Map<Id,Map<string,Opportunity_ARR_Movement__c>> mvmtsMap = new Map<Id,Map<string,Opportunity_ARR_Movement__c>>();
    public List<Sales_KPI_Conditions__mdt> salesKPIMdt = new List<Sales_KPI_Conditions__mdt>();
    public List<Opportunity_ARR_Movement__c> mvmtsToCreate = new List<Opportunity_ARR_Movement__c>();
    public List<Opportunity_ARR_Movement__c> mvmtsToUpdate = new List<Opportunity_ARR_Movement__c>();
    public Map<Id,string> oemMap = new Map<Id,string>();
    public Set<Id> oemIds = new Set<Id>();
    public List<Opportunity> dateChangedOpps = new List<Opportunity>();
    public boolean reportingConditions;
    public boolean condition;
    public string fieldName;
    public boolean updateDates;
    public boolean isOEM;
    /********************************
* Method to prepare the data required for creating or updating opportunity ARR Movements
********************************/    
    public void oppARRMovementsData(List<Opportunity> opps,Map<Id,Opportunity> oppMap){
        //Iterate through list of oportunities updated to store opp Id's in a set
        for(opportunity op: opps){
            oppIds.add(op.Id);
            if(op.OEM__c!=null)
                oemIds.add(op.OEM__c); 
        }
        if(oemIds.size()>0){
            for(account acc:[select id,name from account where id IN:oemIds]){
                oemMap.put(acc.id,acc.name);
            }
        }
            
        //Query the opportunity ARR movements of all updated opportunities
        List<Opportunity_ARR_Movement__c> mvmtsList = [Select id,Opportunity__c,Amount__c,Movement_Type__c,Reporting_Date__c,Status__c from Opportunity_ARR_Movement__c where Opportunity__c IN:oppIds and Status__c = 'Active'];
        //Iterate through list of oportunities and opportunity ARR movements to create a map for storing movements associated with each opportunity.
        for(opportunity op: opps){
            for(Opportunity_ARR_Movement__c mvmt: mvmtsList){
                if(mvmt.Opportunity__c == op.Id){
                    if(!mvmtsMap.containsKey(op.Id)){
                        mvmtsMap.put(op.Id,new Map<string,Opportunity_ARR_Movement__c>());
                        mvmtsMap.get(op.Id).put(mvmt.Movement_Type__c,mvmt);
                    }else{
                        mvmtsMap.get(op.Id).put(mvmt.Movement_Type__c,mvmt);
                    }
                }
            }
        }
        system.debug('Existing movements:'+mvmtsMap);
        //Query custom metadata records storing sales KPI conditions for movements and reporting date
        salesKPIMdt = [select id,Movement_Field__c,Opportunity_Type__c,Movement_Type__c,Movement_Field__r.QualifiedAPIName,Reporting_Date_Criteria_Field_1__r.QualifiedAPIName,Criteria_logical_operator__c,Reporting_Date_Criteria_Field_2__r.QualifiedAPIName,Reporting_Date__r.QualifiedAPIName,Parent_Object__c,Reporting_Date__c,Reporting_Date_to_Close_Date__r.QualifiedAPIName,ARR_Movement_Field__r.QualifiedAPIName from Sales_KPI_Conditions__mdt];
        if(salesKPIMdt.size()>0){
            manageARRMovementChanges(opps,oppMap);
        }
        
    }
    /********************************
* Method for creating or updating opportunity ARR Movements when ARR movements on opportunity are changed is implemented
********************************/  
    public void manageARRMovementChanges(List<Opportunity> opps,Map<Id,Opportunity> oppMap){
        system.debug('Conditions:'+salesKPIMdt);
        for(opportunity op: opps){
            for(Sales_KPI_Conditions__mdt cdns: salesKPIMdt){//Iterate through the list of Sales KPI Conditions metadata records
                system.debug('Condition:'+cdns);
                //Check if the opportunity type mentioned in Sales KPI conditions is matching with the opportunity type
                if((cdns.Opportunity_Type__c).contains(op.Type)){
                    fieldName = cdns.Movement_Field__r.QualifiedAPIName;
                    reportingConditions = false;
                    condition = false;
                    updateDates = false;
                    isOEM = false;
                    boolean mvmtExist = mvmtsMap.containsKey(op.id) && mvmtsMap.get(op.id).get(cdns.Movement_Type__c) != null;
                    //Logic to create or update Opportunity ARR movements when ARR movements on opportunities are changed
                    system.debug('New Movement value:'+(Decimal)(op.get(fieldName)));
                    system.debug('Old Movement value:'+(Decimal)(oppMap.get(op.id).get(fieldName)));
                    if(( (Decimal)(op.get(fieldName)) != (Decimal)(oppMap.get(op.id).get(fieldName))) || ( (Decimal)(op.get(fieldName)) == (Decimal)(oppMap.get(op.id).get(fieldName)) && !mvmtExist)){
                        if(!mvmtsMap.containsKey(op.id) || mvmtsMap.get(op.id).get(cdns.Movement_Type__c) == null ){
                            if((Decimal)(op.get(fieldName)) != 0 && (Decimal)(op.get(fieldName)) != null){
                                createARRMovements(op,cdns,true,false,false);
                            }
                        }else if(mvmtExist){
                            if((Decimal)(op.get(fieldName)) != 0 && (Decimal)(op.get(fieldName)) != null){
                                createARRMovements(op,cdns,true,false,false);
                            }
                            updateARRMovements(op,cdns);                     
                        }
                    }
                    //Logic to update Opportunity ARR movements when opportunity is reopened
                    if((op.StageName !=oppMap.get(op.id).StageName && oppMap.get(op.id).StageName == 'Closed Won') && mvmtExist){
                        updateARRMovements(op,cdns);
                    }
                    //Logic to create or update Opportunity ARR movements when close date or contract start date are changed
                    if(((op.CloseDate !=oppMap.get(op.id).CloseDate) || ((op.Startdate_contract__c !=oppMap.get(op.id).Startdate_contract__c)&&!op.Reporting_Date_to_Close_Date__c)
                       || (((boolean)op.get(cdns.Reporting_Date_to_Close_Date__r.QualifiedAPIName) !=oppMap.get(op.id).Reporting_Date_to_Close_Date__c) && !(boolean)op.get(cdns.Reporting_Date_to_Close_Date__r.QualifiedAPIName)))
                       && mvmtExist){
                        system.debug('Inside Close date');
                        createARRMovements(op,cdns,false,true,false);
                        if(updateDates){
                            updateARRMovements(op,cdns);
                        }
                    }
                    //Logic to create or update Opportunity ARR movements when reporting date to close date is checked on opportunity
                    if(((boolean)op.get(cdns.Reporting_Date_to_Close_Date__r.QualifiedAPIName) !=oppMap.get(op.id).Reporting_Date_to_Close_Date__c) &&(boolean)op.get(cdns.Reporting_Date_to_Close_Date__r.QualifiedAPIName) && mvmtExist && (mvmtsMap.get(op.id).get(cdns.Movement_Type__c).Reporting_Date__c != op.CloseDate)){
                        createARRMovements(op,cdns,false,false,true);
                        updateARRMovements(op,cdns);
                    }
                }
            }
        }
        //Create Opportunity ARR Movements
        if(mvmtsToCreate.size() > 0)
            insert mvmtsToCreate;
        //Update Opportunity ARR Movements
        system.debug('Update Movements:'+mvmtsToUpdate);
        if(mvmtsToUpdate.size() > 0)
            update mvmtsToUpdate;
    }
    /********************************
* Method for creating opportunity ARR Movements 
********************************/  
    public void createARRMovements(opportunity op,Sales_KPI_Conditions__mdt cdns,boolean mvmtsChanged,boolean datesChanged,boolean closeDateAsReporting){
        //Check if reporting date to close date is checked on opportunity
        if((boolean)op.get(cdns.Reporting_Date_to_Close_Date__r.QualifiedAPIName) && !closeDateAsReporting){
            closeDateAsReporting = true;
        }else{
            // Compare the dates based on conditions in sales KPI conditions metadata to map the reporting date
            if(cdns.Reporting_Date_Criteria_Field_1__c !=null && cdns.Reporting_Date_Criteria_Field_2__c !=null && cdns.Criteria_logical_operator__c !=null){
                reportingConditions = true;
                object value1 = op.get(cdns.Reporting_Date_Criteria_Field_1__r.QualifiedAPIName);
                object value2 = op.get(cdns.Reporting_Date_Criteria_Field_2__r.QualifiedAPIName); 
                if(cdns.Criteria_logical_operator__c == '>'?(Date)(value1) >= (Date)(value2):(Date)(value1) < (Date)(value2)){
                    condition =true;
                }
            }
        }
        // Check when dates are changed on opportunity, existing reporting date is matching with new reporting date or not
        if(datesChanged && (condition || !reportingConditions) && (mvmtsMap.get(op.id).get(cdns.Movement_Type__c).Reporting_Date__c !=(Date)(op.get(cdns.Reporting_Date__r.QualifiedAPIName)))){
            updateDates = true;
        }
        if((cdns.Movement_Type__c =='New ARR' && op.OEM__c !=null && (oemMap.get(op.OEM__c) ==system.label.OEM_Workfront || oemMap.get(op.OEM__c) ==system.label.OEM_Acquia))
           ||(cdns.Movement_Type__c =='New ARR: OEM' && (op.OEM__c ==null||(op.OEM__c !=null && oemMap.get(op.OEM__c) !=system.label.OEM_Workfront && oemMap.get(op.OEM__c) !=system.label.OEM_Acquia)))){
            isOEM = true;
        }
        system.debug('Conditionsss:'+condition+';'+reportingConditions+op.OEM__r.name+system.label.OEM_Workfront);
        if(((mvmtsChanged && (condition || !reportingConditions)) || updateDates || closeDateAsReporting) && !isOEM){
            Opportunity_ARR_Movement__c mvmt = new Opportunity_ARR_Movement__c();
            mvmt.Amount__c = (Decimal)(op.get(cdns.ARR_Movement_Field__r.QualifiedAPIName));
            mvmt.Movement_Type__c = cdns.Movement_Type__c;
            mvmt.Opportunity__c = op.Id;
            mvmt.CurrencyIsoCode = op.CurrencyIsoCode;
            // Update close date as reporting date when reporting date to close date is checked, otherwise reporting date based on conditions
            mvmt.Reporting_Date__c = closeDateAsReporting?op.CloseDate:(Date)(op.get(cdns.Reporting_Date__r.QualifiedAPIName));
                if(!mvmtsToCreate.contains(mvmt))
                mvmtsToCreate.add(mvmt);
        }     
    }
    /********************************
* Method for updating opportunity ARR Movements 
********************************/ 
    public void updateARRMovements(opportunity op,Sales_KPI_Conditions__mdt cdns){
        mvmtsMap.get(op.id).get(cdns.Movement_Type__c).Status__c = 'Obsolete';
        mvmtsMap.get(op.id).get(cdns.Movement_Type__c).Status_Modified_Date__c = system.today();
        if(!mvmtsToUpdate.contains(mvmtsMap.get(op.id).get(cdns.Movement_Type__c)))
            mvmtsToUpdate.add(mvmtsMap.get(op.id).get(cdns.Movement_Type__c));  
    }
}